### ISSUE TITLE
Export Data.IntPSQ.unsafeInsertNew

### ISSUE THREAD

**Issue by mitchellwrosen** [jaspervdj/psqueues#28]
I was poking around the innards and `unsafeInsertNew` caught my eye - also the fact that every `insert` first does a `delete`!

Could `unsafeInsertNew` be exported? I happen to have an `IntPSQ` whose keys are pulled from a unique int supply so I'm confident they don't already exist. I could benefit from avoiding an unnecessary `delete`.

Thanks a lot :)

**Comment by jaspervdj** [comment]
Released this as `0.2.7.0`
