### ISSUE TITLE
Support hashable-1.3.0.0

### ISSUE THREAD

**Issue by int-e** [jaspervdj/psqueues#31]
There is a new major release of [hashable](https://hackage.haskell.org/package/hashable-1.3.0.0). As far as I can see, bumping the upper bound is enough to support it.

Interestingly, this is actually causing problems at the moment (`cabal-install` is having a hard time finding installation plans, e.g. https://github.com/lambdabot/lambdabot/issues/183).

**Comment by int-e** [comment]
ping?

**Comment by jaspervdj** [comment]
Done!
