### ISSUE TITLE
hashable-1.5 not accepted

### ISSUE THREAD

**Issue by ysangkok** [jaspervdj/psqueues#58]
v0.2.8.0 of psqueues doesn't accept hashable-1.5, which was released in June 2024. That would be nice since this release has a [few nice features](https://hackage.haskell.org/package/hashable-1.5.0.0/changelog).

**Comment by jaspervdj** [comment]
Thanks!  I bumped the dependency and released a metadata revision on Hackage.

**Comment by ysangkok** [comment]
Thank you, I will close this since the fix is committed and available on Hackage.
